version: "3.8"

services:
  flask:
    build: ./flask
    environment:
      - APP_NAME=Amatsuriki
      - DATABASE_URL=postgresql://postgres_n:postgres_p@db:5432/db_name  # DB connection string
      - REDIS_URL=redis://redis:6379/0  # Redis connection string
    volumes:
      - ./flask:/app
    ports:
      - 8080
    depends_on:
      - db
      - redis

  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: postgres_n
      POSTGRES_PASSWORD: postgres_p
    ports:
      - "5432:5432"

  redis:
    image: redis

  nginx:
    build: ./nginx
    container_name: amatsuriki_nginx
    # restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask
